service: paytel-admin-api

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  flag-transaction:
    handler: flag-transaction.main
    events:
      - http:
          path: transactions/{transaction_id}
          method: put
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              paths:
                transaction_id: true
  get-transaction:
    handler: get-transaction.main
    events:
      - http:
          path: transactions/{transaction_id}
          method: get
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              paths:
                transaction_id: true
  get-transactions:
    handler: get-transactions.main
    events:
      - http:
          path: transactions
          method: get
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              querystrings:
                t: false
                b: false
                s: false
                u: false
  get-transactions-flagged:
    handler: get-transactions-flagged.main
    events:
      - http:
          path: transactions/flagged
          method: get
          cors: true
          authorizer: aws_iam
  get-user:
    handler: get-user.main
    events:
      - http:
          path: users/{user_id}
          method: get
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              paths:
                user_id: true
  get-users:
    handler: get-users.main
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              querystrings:
                u: false
                f: false
                l: false
